from quantcore.paths import DATA_DIR, PROJECT_ROOT, RESULTS_DIR as PROJECT_RESULTS_DIR


ROOT = PROJECT_ROOT
FUTURES_DATA_ROOT = DATA_DIR / "futures"
FUTURES_RAW_DIR = FUTURES_DATA_ROOT / "raw"
FUTURES_PROCESSED_DIR = FUTURES_DATA_ROOT / "processed"
FUTURES_RESULTS_DIR = PROJECT_RESULTS_DIR / "futures"
