"""A-share data provider interfaces."""

from .tushare import (
    END_DATE,
    EXCHANGE,
    INDEX_CODE,
    START_DATE,
    fetch_adj_factor_all,
    fetch_codes_from_universe,
    fetch_daily_all,
    fetch_daily_basic_all,
    fetch_index_weight,
    fetch_index_daily,
    fetch_latest_hs300_universe,
    fetch_stock_basic,
    fetch_stock_st,
    fetch_stk_limit,
    fetch_suspend_d,
    fetch_trade_dates,
    fetch_by_codes,
    fetch_by_trade_dates,
    init_tushare_client,
)

__all__ = [
    "START_DATE",
    "END_DATE",
    "INDEX_CODE",
    "EXCHANGE",
    "init_tushare_client",
    "fetch_by_trade_dates",
    "fetch_by_codes",
    "fetch_trade_dates",
    "fetch_codes_from_universe",
    "fetch_latest_hs300_universe",
    "fetch_daily_all",
    "fetch_daily_basic_all",
    "fetch_adj_factor_all",
    "fetch_stk_limit",
    "fetch_index_weight",
    "fetch_suspend_d",
    "fetch_stock_st",
    "fetch_stock_basic",
    "fetch_index_daily",
]
